NODC_OMS/NODC/Controllers/TaskListController.cs
using DataAccess;
using DataAccess.POCO;
using NODC_OMS.Controllers;
using NODC_OMS.Helper;
using NODC_OMS.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace NODC_OMS.Controllers
{
    [HandleError]
    [RedirectingAction]
    public class TaskListController : ControllerBase
    {
        private IUserRepository _usersModel;
        private ICustomerRepository _customersModel;
        private IQuotationRepository _quotationsModel;
        private IQuotationItemDescriptionRepository _quotationItemDescriptionsModel;
        private ITaskListLoadAllRepository _taskListsLoadAllModel;
        private IProjectRepository _projectsModel;
        private IProjectProjectExpensesRepository _projectExpensesModel;
        private IPayoutRepository _payoutsModel;

        // GET: TaskList
        public TaskListController()
            : this(new UserRepository(), new CustomerRepository(), new QuotationRepository(), new QuotationItemDescriptionRepository(), new TaskListLoadAllRepository(), new ProjectRepository(), new ProjectProjectExpensesRepository(), new PayoutRepository())
        {

        }

        public TaskListController(IUserRepository usersModel, ICustomerRepository customersModel, IQuotationRepository quotationsModel, IQuotationItemDescriptionRepository quotationItemDescriptionsModel, ITaskListLoadAllRepository taskListsLoadAllModel, IProjectRepository projectsModel, IProjectProjectExpensesRepository projectExpensesModel, IPayoutRepository payoutsModel)
        {
            _usersModel = usersModel;
            _customersModel = customersModel;
            _quotationsModel = quotationsModel;
            _quotationItemDescriptionsModel = quotationItemDescriptionsModel;
            _taskListsLoadAllModel = taskListsLoadAllModel;
            _projectsModel = projectsModel;
            _projectExpensesModel = projectExpensesModel;
            _payoutsModel = payoutsModel;
        }

        // GET: TaskList
        public ActionResult Index()
        {
            return RedirectToAction("Listing");
        }

        //GET: Listing
        public ActionResult Listing(int page = 1)
        {

            int loginMainID = Convert.ToInt32(Session["MainID"]);

            User user = _usersModel.GetSingle(loginMainID);

            //the 4 boxes value
            decimal RealizedProfit = 0; //profit has been paid ( check from project status is completed and get all the amount from quotation )
            decimal PendingPayout = 0; //profit not yet pay ( check from payout status is Unpaid )
            decimal ActiveProjectAmount = 0; //amount has been paid ( check from payout status is Completed )
            decimal ToNextTier = 0; // amount needed to promote to next level 

            //Active Project Amount
            List <Project> getProjectQuotationId = _projectsModel.GetAll().Where(e => e.CoordinatorId == loginMainID && e.Status == "Active" && e.IsDeleted == "N").ToList();

            foreach (Project _getProjectQuotationId in getProjectQuotationId)
            {
                //get quotationID, sum all the quotation item description amount
                List<QuotationItemDescription> getAllItemDescription = _quotationItemDescriptionsModel.getAllRelatedIdGetAllRelatedQuotationId(_getProjectQuotationId.QuotationReferenceId);

                foreach(QuotationItemDescription _getAllItemDescrition in getAllItemDescription)
                {
                    ActiveProjectAmount += _getAllItemDescrition.QuotationItemAmount;
                }
            }

            ViewData["ActiveProjectAmount"] = ActiveProjectAmount.ToString("#,##0.00");

            //Get Realized Profit ( from payout already paid )
            List<Payout> getAllPayout = null;

            if (user.Role == "Sales")
            {
                getAllPayout = _payoutsModel.GetAll(loginMainID, "Salesperson").Where(e => e.Status == "Completed").ToList();
            }
            else if(user.Role == "Customer")
            {
                _payoutsModel.GetAll(loginMainID, "Customer").Where(e => e.Status == "Completed").ToList();
            }

            if(getAllPayout != null)
            {
                foreach (Payout _getAllPayout in getAllPayout)
                {
                    RealizedProfit += _getAllPayout.TotalPayoutAmount;
                }
            }

            ViewData["RealizedProfit"] = RealizedProfit.ToString("#,##0.00");

            //Get Pending Payout ( from payout not yet paid == Unpaid)
            List<Payout> getAllUnpaidPayout = null;

            if(user.Role == "Sales")
            {
                getAllUnpaidPayout = _payoutsModel.GetAll(loginMainID, "Salesperson").Where(e => e.Status == "Unpaid").ToList();
            }
            else if (user.Role == "Customer")
            {
                getAllUnpaidPayout = _payoutsModel.GetAll(loginMainID, "Customer").Where(e => e.Status == "Unpaid").ToList();
            }

            if(getAllUnpaidPayout != null)
            {
                foreach (Payout _getAllUnpaidPayout in getAllUnpaidPayout)
                {
                    PendingPayout += _getAllUnpaidPayout.TotalPayoutAmount;
                }
            }

            ViewData["PendingPayout"] = PendingPayout.ToString("#,##0.00");

            //Get To next tier promotion calculation
            if(user.Role == "Sales")
            {
                string userPosition = user.Position;
                decimal totalCompletedProfit = user.TotalCompletedProfit;

                if(userPosition == "Consultant")
                {
                    if (totalCompletedProfit < 120000)
                    {
                        ToNextTier = 119999 - totalCompletedProfit;
                        //promotion = "Assistant Manager";
                        //hasPromoted = true;
                    }
                    else if (totalCompletedProfit >= 120000 && totalCompletedProfit < 370000)
                    {
                        //promotion = "Manager";
                        //hasPromoted = true;
                        ToNextTier = 370000 - totalCompletedProfit;
                    }
                    else if (totalCompletedProfit >= 370000)
                    {

                        //ToNextTier = 369999 - totalCompletedProfit;
                        //if (managerAboveCount >= 3)
                        //{
                        //    promotion = "Senior Manager";
                        //    hasPromoted = true;
                        //}
                        //else
                        //{
                        //    promotion = "Manager";
                        //    hasPromoted = true;
                        //}
                    }
                }
                else if(userPosition == "Assistant Manager")
                {
                    if (totalCompletedProfit >= 120000 && totalCompletedProfit < 370000)
                    {
                        ToNextTier = 370000 - totalCompletedProfit;
                        //promotion = "Manager";
                        //hasPromoted = true;
                    }
                    else if (totalCompletedProfit >= 370000)
                    {
                        //ToNextTier = 369999 - totalCompletedProfit;
                        //if (managerAboveCount >= 3)
                        //{
                        //    promotion = "Senior Manager";
                        //    hasPromoted = true;
                        //}
                        //else
                        //{
                        //    promotion = "Manager";
                        //    hasPromoted = true;
                        //}
                    }
                }
            }

            ViewData["ToNextTier"] = ToNextTier.ToString("#,##0.00");

            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PageSize"]);
            Session.Add("Page", page);
            Session.Add("PageSize", pageSize);

            //List All Related Items to New List
            IList<Customer> AllCustomer = _customersModel.GetAllTaskList().Where(e => e.AssignToId == loginMainID).ToList();

            List<TaskListLoadAllRecord> list = new List<TaskListLoadAllRecord>();

            //Loop Customer Information
            foreach (Customer _AllCustomer in AllCustomer)
            {
                int id = _AllCustomer.ID;
                string itemID = _AllCustomer.CustomerID;
                string name = _AllCustomer.ContactPerson;
                string date = String.Format("{0:dd/MM/yyyy}", _AllCustomer.CreatedOn);
                string amount = null;
                string status = _AllCustomer.Status;

                list.Add(new TaskListLoadAllRecord()
                {
                    ID = id,
                    ItemID = itemID,
                    Name = name,
                    Date = date,
                    Amount = amount,
                    Status = status,
                    Type = "Customer"
                });
            }

        //if(user.Role == "Super Admin")
        //{
            //Loop all quotations item
            //get latest quotation, filter out confirmed quotation.
            IList<Quotation> getAllQuotation = _quotationsModel.GetAllLatestQuotationID().Where(e => e.Status != "Confirmed" && e.IsDeleted != "Y").ToList();

            foreach(Quotation _getAllQuotation in getAllQuotation)
            {

                int id = _getAllQuotation.ID;
                string itemID = _getAllQuotation.QuotationID;
                string name = null;

                if (!string.IsNullOrEmpty(_getAllQuotation.CompanyName))
                {
                    name = _getAllQuotation.CompanyName;
                }
                else
                {

NODC_OMS/NODC/Views/TaskList/Listing.cshtml
@using DataAccess
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = ViewData["SiteName"].ToString();
    //ViewBag.PageTitle = "Task List";
    ViewBag.liTaskList = "active";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-3">
        <div class="widget">
            <div class="widget-content padding-30 bg-green-600">
                <div class="counter counter-md counter-inverse text-left">
                    <div class="counter-number-group">
                        <span class="counter-number">$@ViewData["RealizedProfit"]</span>
                    </div>
                    <div class="counter-label text-capitalize">Realized Profit</div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="widget">
            <div class="widget-content padding-30 bg-blue-600">
                <div class="counter counter-md counter-inverse text-left">
                    <div class="counter-number-group">
                        <span class="counter-number">$@ViewData["PendingPayout"]</span>
                    </div>
                    <div class="counter-label text-capitalize">Pending Payout</div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="widget">
            <div class="widget-content padding-30 bg-red-600">
                <div class="counter counter-md counter-inverse text-left">
                    <div class="counter-number-group">
                        <span class="counter-number">$@ViewData["ActiveProjectAmount"]</span>
                    </div>
                    <div class="counter-label text-capitalize">Active Project Amount</div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="widget">
            <div class="widget-content padding-30 bg-orange-600">
                <div class="counter counter-md counter-inverse text-left">
                    <div class="counter-number-group">
                        <span class="counter-number">$@ViewData["ToNextTier"]</span>
                    </div>
                    <div class="counter-label text-capitalize">To next Tier </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-title">Task List</div>
    <div class="panel-body container-fluid">
        <div class="row">
            <div class="col-xlg-12 col-md-12">
                <!-- Table -->
                <div>
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Customer/Company</th>
                                    <th>Date/Time</th>
                                    <th>Amount (SGD)</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    IPagedList<TaskListLoadAllRecord> loadAll = (IPagedList<TaskListLoadAllRecord>)ViewData["loadAll"];
                                    if (loadAll.Count > 0)
                                    {
                                        int page = Convert.ToInt32(Session["Page"]) - 1;
                                        int pageSize = Convert.ToInt32(Session["PageSize"]);
                                        int count = 1;

                                        foreach (TaskListLoadAllRecord _loadAll in loadAll)
                                        {
                                            int col1 = count;
                                            string col2 = "-";
                                            string col3 = "-";
                                            string col4 = "-";
                                            string col5 = "-";
                                            string col6 = _loadAll.Status;

                                            if (!string.IsNullOrEmpty(_loadAll.ItemID))
                                            {
                                                col2 = _loadAll.ItemID;
                                            }

                                            if (!string.IsNullOrEmpty(_loadAll.Name))
                                            {
                                                col3 = _loadAll.Name;
                                            }

                                            if (!string.IsNullOrEmpty(_loadAll.Date))
                                            {
                                                col4 = _loadAll.Date;
                                            }

                                            if (_loadAll.Amount != null)
                                            {
                                                col5 = Convert.ToDecimal(_loadAll.Amount).ToString("#,##0.00");
                                            }

                                            <tr>
                                                <td>@col1</td>
                                                @if (_loadAll.Type == "Customer")
                                                {
                                                    <td><a href="@Url.Action("Edit", _loadAll.Type, new { @id = _loadAll.ID })">@col2</a></td>
                                                }
                                                else
                                                {
                                                    <td><a href="@Url.Action("View", _loadAll.Type, new { @id = _loadAll.ID })">@col2</a></td>
                                                }

                                                <td>@col3</td>
                                                <td>@col4</td>
                                                <td>@col5</td>
                                                <td>@col6</td>
                                                <td class="text-nowrap">
                                                    @if (_loadAll.Type == "Customer")
                                                    {
                                                        if (_loadAll.Status != "Active")
                                                        {
                                                            <button type="button" class="btn btn-sm btn-icon btn-round btn-success" id="@_loadAll.ID" onclick="ActiveCustomer(this.id)" data-toggle="tooltip" data-original-title="Activate"><i class="icon wb-check" aria-hidden="true"></i></button>
                                                        }
                                                    }
                                                    else if (_loadAll.Type == "Quotation")
                                                    {
                                                        //This is quotation
                                                        <a href="@Url.Action("Edit", _loadAll.Type, new { @id = _loadAll.ID })" class="btn btn-sm btn-icon btn-round btn-default" data-toggle="tooltip" data-original-title="Revise Quotation / Variation Orders"><i class="icon wb-edit" aria-hidden="true"></i></a>

                                                        if (_loadAll.Status == "Draft")
                                                        {
                                                            <button type="button" class="btn btn-sm btn-icon btn-round btn-danger" id="@_loadAll.ID" onclick="DeleteDraft(this.id)" data-toggle="tooltip" data-original-title="Delete Draft"><i class="icon wb-close" aria-hidden="true"></i></button>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <button type="button" class="btn btn-sm btn-icon btn-round btn-success" id="@_loadAll.ID" onclick="CompleteProject(this.id)" data-toggle="tooltip" data-original-title="Mark as Completed"><i class="icon wb-check" aria-hidden="true"></i></button>
                                                    }
                                                </td>
                                            </tr>
                                                    count++;
                                        }

                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="7" class="no-record">No record to display</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>

                    <div class="pagination">
                        @Html.PagedListPager((IPagedList)ViewData["loadAll"], page => Url.Action("/Listing", "TaskList", new { page, currentFilter = ViewBag.CurrentFilter }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< First", LinkToPreviousPageFormat = "< Previous", LinkToNextPageFormat = "Next >", LinkToLastPageFormat = "Last >>" })
                    </div>
                </div>
                <!-- End Table -->
            </div>
        </div>
    </div>
</div>

@if (Session["Result"] != null)
{
    string[] result = Session["Result"].ToString().Split('|');

    <script>
        $(document).ready(function () {
            alertify.alert("@result[1]");
        })
    </script>

    Session.Remove("Result");
}

<script>
    function ActiveCustomer(clicked_id) {
        alertify.confirm("You are activate this customer! Continue?", function (e) {
            if (e) {
                var url = "@Url.Action("Active", "Customer")";
                var id = clicked_id;

                window.location = url + "?id=" + id;
            }
        });
    }

    function CompleteProject(clicked_id) {
        alertify.confirm("You are marking this project as Complete! Continue?", function (e) {
            if (e) {
                var url = "@Url.Action("Complete", "Project")";
                var id = clicked_id;
                var fromTaskList = "Yes";
                window.location = url + "?id=" + id + "&fromTaskList=" + fromTaskList;
            }
        });
    }

    function DeleteDraft(clicked_id) {
        alertify.confirm("You are deleting this draft! Continue?", function (e) {
            if (e) {
                var url = "@Url.Action("Delete", "TaskList")";
                var id = clicked_id;

                window.location = url + "?id=" + id;
            }
        });
    }
</script>