NODC_OMS/NODC/Models/AuditLog/AuditLogRepository.cs
using DataAccess;
using DataAccess.POCO;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NODC_OMS.Models
{
    public class AuditLogRepository : IAuditLogRepository
    {
        private NODC_OMSContext db;

        public AuditLogRepository()
        {
            db = new NODC_OMSContext();
        }

        public IQueryable<AuditLog> Select()
        {
            var result = from a in db.AuditLogs select a;

            return result;
        }

        public IList<AuditLog> GetAll(string tableName, string startDate, string endDate)
        {
            try
            {
                IQueryable<AuditLog> records = Select();

                if (!string.IsNullOrEmpty(tableName))
                {
                    records = records.Where(e => e.TableAffected == tableName);
                }

                if (!string.IsNullOrEmpty(startDate))
                {
                    DateTime start = Convert.ToDateTime(startDate + " 00:00:00");

                    records = records.Where(e => e.Timestamp >= start);
                }

                if (!string.IsNullOrEmpty(endDate))
                {
                    DateTime end = Convert.ToDateTime(endDate + " 23:59:59");

                    records = records.Where(e => e.Timestamp <= end);
                }

                return records.OrderByDescending(e => e.Timestamp).ToList();
            }
            catch
            {
                throw;
            }
        }

        public IList<AuditLog> GetAll(int userid)
        {
            try
            {
                var records = Select();

                if (userid > 0)
                {
                    records = records.Where(e => e.UserTriggeringId == userid);
                }

                return records.OrderByDescending(e => e.Timestamp).ToList();
            }
            catch
            {
                throw;
            }
        }

        public IPagedList<AuditLog> GetPaged(string tableName, string startDate, string endDate, int page, int size)
        {
            try
            {
                IQueryable<AuditLog> records = Select();

                if (!string.IsNullOrEmpty(tableName))
                {
                    records = records.Where(e => e.TableAffected == tableName);
                }

                if (!string.IsNullOrEmpty(startDate))
                {
                    DateTime start = Convert.ToDateTime(startDate + " 00:00:00");

                    records = records.Where(e => e.Timestamp >= start);
                }

                if (!string.IsNullOrEmpty(endDate))
                {
                    DateTime end = Convert.ToDateTime(endDate + " 23:59:59");

                    records = records.Where(e => e.Timestamp <= end);
                }

                return records.OrderByDescending(e => e.Timestamp).ToPagedList(page, size);
            }
            catch
            {
                throw;
            }
        }

        public IList<AuditLog> GetUniqueTable()
        {
            try
            {
                IQueryable<AuditLog> records = Select();

                records = records.GroupBy(g => g.TableAffected).Select(group => group.FirstOrDefault());

                return records.OrderBy(e => e.TableAffected).ToList();
            }
            catch
            {
                throw;
            }
        }

        public bool Add(AuditLog data)
        {
            try
            {
                data.Timestamp = DateTime.Now;

                db.AuditLogs.Add(data);

                db.SaveChanges();

                return true;
            }
            catch
            {
                throw;
            }
        }
    }
}

NODC_OMS/NODC/Models/AuditLog/IAuditLogRepository.cs
using DataAccess.POCO;
using PagedList;
using System.Collections.Generic;

namespace NODC_OMS.Models
{
    public interface IAuditLogRepository
    {
        IList<AuditLog> GetAll(string tableName, string startDate, string endDate);

        IList<AuditLog> GetAll(int userid);

        IPagedList<AuditLog> GetPaged(string tableName, string startDate, string endDate, int page, int size);

        IList<AuditLog> GetUniqueTable();

        bool Add(AuditLog data);
    }
}

NODC_OMS/NODC/Controllers/AuditLogController.cs
using DataAccess.POCO;
using NODC_OMS.Models;
using NODC_OMS.Controllers;
using PagedList;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace NODC_OMS.Controllers
{
    [HandleError]
    [RedirecttingActionAdmin]
    [RedirecttingActionAuditLog]
    public class AuditLogController : ControllerBase
    {
        private IAuditLogRepository _auditLogsModel;
        private IUserRepository _usersModel;

        public AuditLogController()
            : this(new AuditLogRepository(), new UserRepository())
        {

        }

        public AuditLogController(IAuditLogRepository auditLogsModel, IUserRepository usersModel)
        {
            _auditLogsModel = auditLogsModel;
            _usersModel = usersModel;
        }

        // GET: AuditLog
        public ActionResult Index()
        {
            if (Session["LogTable"] != null)
            {
                Session.Remove("LogTable");
            }

            if (Session["FromDate"] != null)
            {
                Session.Remove("FromDate");
            }

            if (Session["ToDate"] != null)
            {
                Session.Remove("ToDate");
            }

            if (Session["Page"] != null)
            {
                Session.Remove("Page");
            }

            if (Session["PageSize"] != null)
            {
                Session.Remove("PageSize");
            }

            return RedirectToAction("Options");
        }

        //GET: Options
        public ActionResult Options()
        {
            string logTable = "";

            if (Session["LogTable"] != null)
            {
                logTable = Session["LogTable"].ToString();
            }

            ViewData["FromDate"] = DateTime.Now.ToString("dd/MM/yyyy");

            if (Session["FromDate"] != null)
            {
                ViewData["FromDate"] = Session["FromDate"];
            }

            ViewData["ToDate"] = DateTime.Now.ToString("dd/MM/yyyy");

            if (Session["ToDate"] != null)
            {
                ViewData["ToDate"] = Session["ToDate"];
            }

            Dropdown[] logTableDDL = LogTableDropdown();
            ViewData["LogTableDropdown"] = new SelectList(logTableDDL, "val", "name", logTable);

            ViewData["SiteName"] = ConfigurationManager.AppSettings["SiteName"].ToString();
            return View();
        }

        //POST: Options
        [HttpPost]
        public ActionResult Options(FormCollection form)
        {
            DateTime fromDate = DateTime.Now;
            DateTime toDate = DateTime.Now;

            if (!string.IsNullOrEmpty(form["FromDate"]))
            {
                try
                {
                    fromDate = Convert.ToDateTime(form["FromDate"].ToString());
                }
                catch
                {
                    ModelState.AddModelError("FromDate", "From Date is not valid!");
                }
            }

            if (!string.IsNullOrEmpty(form["ToDate"]))
            {
                try
                {
                    toDate = Convert.ToDateTime(form["ToDate"].ToString());
                }
                catch
                {
                    ModelState.AddModelError("ToDate", "To Date is not valid!");
                }
            }

            if (fromDate > toDate)
            {
                ModelState.AddModelError("ToDate", "To Date is earlier than From Date!");
            }

            if (ModelState.IsValid)
            {
                Session.Add("LogTable", form["LogTable"].ToString());
                Session.Add("FromDate", form["FromDate"].ToString());
                Session.Add("ToDate", form["ToDate"].ToString());
                return RedirectToAction("Listing");
            }
            else
            {
                Session.Add("Result", "danger|There is something wrong in the form!");
            }

            Dropdown[] logTableDDL = LogTableDropdown();
            ViewData["LogTableDropdown"] = new SelectList(logTableDDL, "val", "name", form["LogTable"].ToString());

            ViewData["FromDate"] = form["FromDate"].ToString();
            Session.Add("FromDate", form["FromDate"].ToString());

            ViewData["ToDate"] = form["ToDate"].ToString();
            Session.Add("ToDate", form["ToDate"].ToString());

            ViewData["SiteName"] = ConfigurationManager.AppSettings["SiteName"].ToString();
            return View();
        }

        //GET: Listing
        public ActionResult Listing(int page = 1)
        {
            int pageSize = 20;
            if (Session["PageSize"] != null)
            {
                pageSize = Convert.ToInt32(Session["PageSize"]);
            }
            Session.Add("Page", page);
            Session.Add("PageSize", pageSize);

            string tableAffected = Session["LogTable"].ToString();
            string fromDate = Session["FromDate"].ToString();
            string toDate = Session["ToDate"].ToString();

            IPagedList<AuditLog> logs = _auditLogsModel.GetPaged(tableAffected, fromDate, toDate, page, pageSize);
            ViewData["AuditLogs"] = logs;

            Dropdown[] pageSizeDDL = PageSizeDDL();
            ViewData["PageSizeDropdown"] = new SelectList(pageSizeDDL, "val", "name", pageSize.ToString());

            ViewData["SiteName"] = ConfigurationManager.AppSettings["SiteName"].ToString();
            return View();
        }

        //POST: Listing
        [HttpPost]
        public ActionResult Listing(FormCollection form)
        {
            int page = 1;
            int pageSize = Convert.ToInt32(form["PageSize"]);
            Session.Add("Page", page);
            Session.Add("PageSize", pageSize);

            string tableAffected = Session["LogTable"].ToString();
            string fromDate = Session["FromDate"].ToString();
            string toDate = Session["ToDate"].ToString();

            IPagedList<AuditLog> logs = _auditLogsModel.GetPaged(tableAffected, fromDate, toDate, page, pageSize);
            ViewData["AuditLogs"] = logs;

            Dropdown[] pageSizeDDL = PageSizeDDL();
            ViewData["PageSizeDropdown"] = new SelectList(pageSizeDDL, "val", "name", pageSize.ToString());

            ViewData["SiteName"] = ConfigurationManager.AppSettings["SiteName"].ToString();
            return View();
        }

        //GET: ExportExcel
        public void ExportExcel(string logTable, string fromDate, string toDate, int page = 0, int pageSize = 0)
        {
            IList<AuditLog> logs = null;

            if (page <= 0)
            {
                logs = _auditLogsModel.GetAll(logTable, fromDate, toDate);
            }
            else
            {
                logs = _auditLogsModel.GetPaged(logTable, fromDate, toDate, page, pageSize).ToList();
            }

            using (ExcelPackage pck = new ExcelPackage())
            {
                //Create the worksheet
                ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Audit Logs");

                //set first row name
                ws.Cells[1, 1].Value = "Number";
                ws.Cells[1, 2].Value = "Log ID";
                ws.Cells[1, 3].Value = "IP Address";
                ws.Cells[1, 4].Value = "Timestamp";
                ws.Cells[1, 5].Value = "User Triggering";
                ws.Cells[1, 6].Value = "Table Affected";
                ws.Cells[1, 7].Value = "Description";

                int rowCount = 2;
                int NumCount = 1;
                foreach (AuditLog log in logs)
                {
                    ws.Cells[rowCount, 1].Value = NumCount;
                    ws.Cells[rowCount, 2].Value = log.ID;
                    ws.Cells[rowCount, 3].Value = log.IPAddress;
                    ws.Cells[rowCount, 4].Value = log.Timestamp.ToString("dd/MM/yyyy HH:mm:ss");
                    if (log.UserRole == "System")
                    {
                        ws.Cells[rowCount, 5].Value = "System";
                    }
                    else if(log.UserRole == "Customer")
                    {
                       ws.Cells[rowCount, 5].Value = log.Customer.CustomerID;
                    }
                    else
                    {
                       ws.Cells[rowCount, 5].Value = log.User.UserID;
                    }
                   
                    ws.Cells[rowCount, 6].Value = log.TableAffected;
                    ws.Cells[rowCount, 7].Value = log.Description;
                    rowCount++;
                    NumCount++;
                }

                ws.Cells[ws.Dimension.Address].AutoFitColumns();
                //Write it back to the client
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;  filename=auditlogs-" + DateTime.Now.ToString("yyyyMMddHHmm") + ".xlsx");
                Response.BinaryWrite(pck.GetAsByteArray());
            }
        }

        //LogTable Dropdown
        public Dropdown[] LogTableDropdown()
        {
            IList<AuditLog> uniqueTables = _auditLogsModel.GetUniqueTable().Where(e => e.TableAffected != "QuotationItemDescriptions").ToList();

            Dropdown[] ddl = new Dropdown[uniqueTables.Count + 1];
            ddl[0] = new Dropdown { name = "All Tables", val = "" };

            int count = 1;

            foreach (AuditLog log in uniqueTables)
            {
                ddl[count] = new Dropdown { name = log.TableAffected, val = log.TableAffected };
                count++;
            }

            return ddl;
        }

        //PageSize Dropdown
        public Dropdown[] PageSizeDDL()
        {
            Dropdown[] ddl = new Dropdown[5];
            ddl[0] = new Dropdown { name = "20", val = "20" };

NODC_OMS/NODC/Views/AuditLog/Listing.cshtml
@using DataAccess.POCO
@using PagedList
@using PagedList.Mvc

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = ViewData["SiteName"].ToString();
    ViewBag.PageTitle = "Audit Log";
    ViewBag.AAuditLog = "active open";
}

<div class="page-content container-fluid">
    <div class="panel">
        <div class="panel-body container-fluid">
            <div class="row form-group">
                <a href="@Url.Action("ExportExcel", new { @logTable = Session["LogTable"].ToString(), @fromDate = Session["FromDate"].ToString(), @toDate = Session["ToDate"].ToString(), @page = Convert.ToInt32(Session["Page"]), @pageSize = Convert.ToInt32(Session["PageSize"]) })" class="btn btn-primary" style="float:left;margin-right:10px;">Download to Excel</a>
                <a href="@Url.Action("Options")" class="btn btn-default" style="float:left;">Back</a>
                @using (Html.BeginForm("Listing", "AuditLog", FormMethod.Post, new { @id = "page-size" }))
                {
                    <div class="col-md-3 pull-right">
                        @Html.DropDownList("PageSize", (SelectList)ViewData["PageSizeDropdown"], new { @class = "form-control", @data_plugin = "selectpicker" })
                    </div>
                    @Html.Label("Page Size:", new { @class = "col-md-3 pull-right", @style = "top:6px;text-align:right;" })
                }
            </div>
            <div class="row">
                <div class="col-xlg-12 col-md-12">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Log ID</th>
                                    <th>IP Address</th>
                                    <th>Timestamp</th>
                                    <th>User Triggering</th>
                                    <th>Table Affected</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    IPagedList<AuditLog> logs = (IPagedList<AuditLog>)ViewData["AuditLogs"];

                                    if (logs.Count > 0)
                                    {
                                        int page = Convert.ToInt32(Session["Page"]) - 1;
                                        int pageSize = Convert.ToInt32(Session["PageSize"]);
                                        int i = 1;

                                        foreach (AuditLog log in logs)
                                        {
                                            <tr>
                                                <td>@(i + page * pageSize)</td>
                                                <td>@log.ID</td>
                                                <td>@log.IPAddress</td>
                                                <td>@log.Timestamp.ToString("dd/MM/yyyy HH:mm:ss")</td>

                                                <td>
                                                    @if (log.UserRole == "System")
                                                    {
                                                        @("System")
                                                    }
                                                    else if (log.UserRole == "Customer") 
                                                    { 
                                                        @log.Customer.CustomerID; 
                                                    } 
                                                    else 
                                                    { 
                                                        @log.User.UserID ; 
                                                    }
                                                </td>
                                                <td>@log.TableAffected</td>
                                                <td>@log.Description</td>
                                            </tr>
                                            i++;
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="7" class="no-records-found">No record to display</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="pagination">
                    @Html.PagedListPager((IPagedList)ViewData["AuditLogs"], page => Url.Action("/Listing", "AuditLog", new { page, currentFilter = ViewBag.CurrentFilter }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< First", LinkToPreviousPageFormat = "< Previous", LinkToNextPageFormat = "Next >", LinkToLastPageFormat = "Last >>" })
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $("#PageSize").on("change", function () {
        $("#page-size").submit();
    });
</script>

NODC_OMS/NODC/Views/AuditLog/Options.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = ViewData["SiteName"].ToString();
    ViewBag.PageTitle = "Audit Log";
    ViewBag.AAuditLog = "active open";
}

<div class="page-content">
    <div class="panel">
        <div class="panel-body container-fluid">
            <div class="row">
                <div class="col-xlg-12 col-md-12">
                    @using (Html.BeginForm("Options", "AuditLog", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        if (Session["Result"] != null)
                        {
                            string[] result = Session["Result"].ToString().Split('|');

                            <div class="alert alert-@result[0] text-center">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                @result[1]
                            </div>

                            Session.Remove("Result");
                        }

                        <div class="form-group">
                            @Html.Label("Log Table", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.DropDownList("LogTable", (SelectList)ViewData["LogTableDropdown"], new { @class = "form-control" })
                                @Html.ValidationMessage("LogTable")
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("From Date", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.TextBox("FromDate", ViewData["FromDate"].ToString(), new { @class = "form-control" })
                                @Html.ValidationMessage("FromDate")
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("To Date", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.TextBox("ToDate", ViewData["ToDate"].ToString(), new { @class = "form-control" })
                                @Html.ValidationMessage("ToDate")
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-9 col-sm-offset-3">
                                <button type="submit" class="btn btn-primary">Generate</button>
                                <button type="button" class="btn btn-primary" onclick="DownloadToExcel()">Download to excel</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="@Url.Content("~/Content/vendor/bootstrap-datepicker/bootstrap-datepicker.js")"></script>

<script>
    $("#FromDate").datepicker({
        endDate: new Date(),
    }).on("changeDate", function () {
        $("#ToDate").datepicker("setStartDate", new Date($("#FromDate").datepicker("getDate")));
    });

    $("#ToDate").datepicker({
        startDate: new Date($("#FromDate").datepicker("getDate")),
        endDate: new Date()
    });

    function DownloadToExcel() {
        var logTable = $("#LogTable").val();
        var fromDate = $("#FromDate").val();
        var toDate = $("#ToDate").val();
        var url = "@Url.Action("ExportExcel")?logTable=" + logTable + "&fromDate=" + fromDate; + "&toDate=" + toDate;
        window.location.href = url;
    }
</script>