NODC_OMS/NODC/Models/Customer/CustomerReminderRepository.cs
using DataAccess;
using DataAccess.POCO;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NODC_OMS.Models
{
    public class CustomerReminderRepository : ICustomerReminderRepository
    {
       private NODC_OMSContext db;

       public CustomerReminderRepository()
       {
            db = new NODC_OMSContext();
       }

       public IQueryable<CustomerReminder> Select()
       {
            var result = from u in db.CustomerReminders select u;

            return result;
       }

       public IList<CustomerReminder> GetAll()
       {
           try
           {
               var records = Select();

               return records.OrderBy(e => e.CustomerId).ToList();
           }
           catch
           {
               throw;
           }
       }

       public IList<CustomerReminder> GetPersonalAll(int id)
       {
           try
           {
               var records = Select();

               return records.Where(e => e.CustomerId == id).OrderBy(e => e.CustomerId).ToList();
           }
           catch
           {
               throw;
           }
       }

       public CustomerReminder GetSingle(int id)
       {
           try
           {
               var records = Select();

               return records.Where(e => e.ID == id).FirstOrDefault();
           }
           catch
           {
               throw;
           }
       }

       public bool Add(CustomerReminder data)
       {
           try
           {

               db.CustomerReminders.Add(data);
               db.SaveChanges();

               return true;
           }
           catch
           {
               throw;
           }
       }

        public bool Update(int id, CustomerReminder updateData)
        {
            try
            {
                CustomerReminder data = db.CustomerReminders.Find(id);

                data.CustomerId = updateData.CustomerId;
                data.Description = updateData.Description;
                data.Date = updateData.Date;
                data.Repeat = updateData.Repeat;

                db.SaveChanges();

                return true;
            }
            catch
            {
                throw;
            }
        }

        public bool Delete(int id)
        {
            try
            {
                CustomerReminder customerReminder = db.CustomerReminders.Find(id);

                db.CustomerReminders.Remove(customerReminder);

                db.SaveChanges();

                return true;
            }
            catch
            {
                throw;
            }
        }
    }
}

NODC_OMS/NODC/Models/Customer/ICustomerReminderRepository.cs
using DataAccess.POCO;
using PagedList;
using System.Collections.Generic;

namespace NODC_OMS.Models
{
    public interface ICustomerReminderRepository
    {
        IList<CustomerReminder> GetAll();

        IList<CustomerReminder> GetPersonalAll(int id);

        CustomerReminder GetSingle(int id);

        bool Add(CustomerReminder data);

        bool Update(int id, CustomerReminder updateData);

        bool Delete(int id);

    }
}

NODC_OMS/NODC/Models/Customer/ICustomerRepository.cs
using DataAccess.POCO;
using PagedList;
using System;
using System.Collections.Generic;

namespace NODC_OMS.Models
{
    public interface ICustomerRepository
    {

        IList<Customer> GetAll();

        IList<Customer> GetCustomerEventsReminder(int assignId, List<string> status, DateTime? reminderDate);

        IList<Customer> GetActiveCustomers();

        IList<Customer> GetAllTaskList();

        IList<Customer> ViewDownline(int id);

        IList<Customer> GetCustomerDownlineWithUserType(int id, string uplineType);

        IList<Customer> GetCustomerDownline(int id);

        IPagedList<Customer> GetPaged(List<int> OwnAndUplineID, string keyword, string status, int page, int size);

        IPagedList<Customer> GetCustomersDataPaged(string startDate, string endDate, int page, int size);

        IList<Customer> GetAllCustomers(string startDate, string endDate);

        IList<Customer> GetAllCommissionReport(string agency, string startDate, string endDate);

        Customer GetSingle(int id);

        Customer GetSingleNoFilter(int id);

        Customer GetLast();

        Customer GetUniqueEmail(string email);

        bool Add(Customer data);

        bool Update(int id, Customer updateData);

        bool PromoteCustomerPosition(int id, decimal totalCompletedProfit, string position);

        bool UpdateData(int id, Customer updateData);

        bool Delete(int id);

        bool Active(int id);

        Customer FindLoginID(string loginID);

        Customer FindPersonalLoginID(int id, string loginID);

        bool AssignResetPassword(int id, string token);
    }
}

NODC_OMS/NODC/Controllers/CustomersController.cs
using DataAccess;
using DataAccess.POCO;
using Newtonsoft.Json;
using NODC_OMS.Controllers;
using NODC_OMS.Helper;
using NODC_OMS.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Services;

namespace NODC_OMS.Controllers
{
    [HandleError]
    [RedirectingActionCustomer]
    public class CustomersController : ControllerBase
    {
        private ICustomerRepository _customersModel;
        private IUserRepository _usersModel;
        private IQuotationRepository _quotationsModel;
        private IQuotationCoBrokeRepository _quotationCoBrokesModel;
        private IQuotationItemDescriptionRepository _quotationItemDescriptionsModel;
        private IProjectRepository _projectsModel;
        private IProjectProjectExpensesRepository _projectExpensesModel;
        private IInvoiceRepository _invoicesModel;
        private IInvoiceItemDescriptionRepository _invoiceItemsModel;
        private ISystemSettingRepository _settingsModel;
        private IPayoutRepository _payoutsModel;
        private IPayoutCalculationRepository _payoutCalculationsModel;

        // GET: TaskList
        public CustomersController()
            : this(new CustomerRepository(), new UserRepository(), new QuotationRepository(),new QuotationCoBrokeRepository(), new QuotationItemDescriptionRepository(), new ProjectRepository(), new ProjectProjectExpensesRepository(), new InvoiceRepository(), new InvoiceItemDescriptionRepository(), new SystemSettingRepository(), new PayoutRepository(), new PayoutCalculationRepository())
        {

        }

        public CustomersController(ICustomerRepository customersModel, IUserRepository usersModel, IQuotationRepository quotationsModel,IQuotationCoBrokeRepository quotationCoBrokesModel, IQuotationItemDescriptionRepository quotationItemDescriptionsModel, IProjectRepository projectsModel, IProjectProjectExpensesRepository projectExpensesModel, IInvoiceRepository invoicesModel, IInvoiceItemDescriptionRepository invoiceItemsModel, ISystemSettingRepository settingsModel, IPayoutRepository payoutsModel, IPayoutCalculationRepository payoutCalculationsModel)
        {
            _customersModel = customersModel;
            _usersModel = usersModel;
            _quotationsModel = quotationsModel;
            _quotationCoBrokesModel = quotationCoBrokesModel;
            _quotationItemDescriptionsModel = quotationItemDescriptionsModel;
            _projectsModel = projectsModel;
            _projectExpensesModel = projectExpensesModel;
            _invoicesModel = invoicesModel;
            _invoiceItemsModel = invoiceItemsModel;
            _settingsModel = settingsModel;
            _payoutsModel = payoutsModel;
            _payoutCalculationsModel = payoutCalculationsModel;
        }

        // GET: Index
        public ActionResult Index(string mod = null)
        {
            if (Session["SearchKeyword"] != null)
            {
                Session.Remove("SearchKeyword");
            }

            switch (mod)
            {
                case "qo": return RedirectToAction("ListingQuotation");
                case "pr": return RedirectToAction("ListingProject");
                case "py": return RedirectToAction("ListingPayout");
                case "iv": return RedirectToAction("ListingInvoice");
                default: return RedirectToAction("ListingQuotation");
            }
        }

        //GET: ListingQuotation
        public ActionResult ListingQuotation(int page = 1)
        {

            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PageSize"]);

            Session.Add("Page", page);
            Session.Add("PageSize", pageSize);

            ViewData["SearchKeyword"] = "";
            ViewData["SearchStatus"] = "";

            string SalesPersonType = "Customer";

            int MainID = Convert.ToInt32(Session["MainID"]);

            IPagedList<Quotation> quotations = _quotationsModel.GetPagedCustomer(ViewData["SearchKeyword"].ToString(), ViewData["SearchStatus"].ToString(), MainID, page, pageSize);

            List<QuotationItemDescription> newTableItemDescriptions = new List<QuotationItemDescription>();

            foreach (Quotation _quotations in quotations)
            {
                int mainID = _quotations.ID;

                List<QuotationItemDescription> quotationsAmount = _quotationItemDescriptionsModel.getAllRelatedIdGetAllRelatedQuotationId(mainID);

                QuotationItemDescription itemRecord = new QuotationItemDescription();

                foreach (QuotationItemDescription _quotationsAmount in quotationsAmount)
                {
                    itemRecord.ID = _quotationsAmount.ID;
                    itemRecord.QuotationId = _quotationsAmount.QuotationId;
                    itemRecord.QuotationItemAmount += _quotationsAmount.QuotationItemAmount;
                }

                newTableItemDescriptions.Add(itemRecord);
            }

            ViewData["Quotation"] = quotations;
            ViewData["GetListingAmount"] = newTableItemDescriptions;

            ViewData["SiteName"] = ConfigurationManager.AppSettings["SiteName"].ToString();
            return View();
        }

        //POST: ListingQuotation
        [HttpPost]
        public ActionResult ListingQuotation(FormCollection form)
        {
            int page = 1;
            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PageSize"]);

            Session.Add("Page", page);
            Session.Add("PageSize", pageSize);

            ViewData["SearchKeyword"] = form["SearchKeyword"].Trim();
            Session.Add("SearchKeyword", form["SearchKeyword"].Trim());

            ViewData["SearchStatus"] = "";

            //string SalesPersonType = "Customer";

            int MainID = Convert.ToInt32(Session["MainID"]);

            IPagedList<Quotation> quotations = _quotationsModel.GetPagedCustomer(ViewData["SearchKeyword"].ToString(), ViewData["SearchStatus"].ToString(), MainID, page, pageSize);

            List<QuotationItemDescription> newTableItemDescriptions = new List<QuotationItemDescription>();

            foreach (Quotation _quotations in quotations)
            {
                int mainID = _quotations.ID;

                List<QuotationItemDescription> quotationsAmount = _quotationItemDescriptionsModel.getAllRelatedIdGetAllRelatedQuotationId(mainID);

                QuotationItemDescription itemRecord = new QuotationItemDescription();

                foreach (QuotationItemDescription _quotationsAmount in quotationsAmount)
                {
                    itemRecord.ID = _quotationsAmount.ID;
                    itemRecord.QuotationId = _quotationsAmount.QuotationId;
                    itemRecord.QuotationItemAmount += _quotationsAmount.QuotationItemAmount;
                }

                newTableItemDescriptions.Add(itemRecord);
            }

            ViewData["Quotation"] = quotations;
            ViewData["GetListingAmount"] = newTableItemDescriptions;

            ViewData["SiteName"] = ConfigurationManager.AppSettings["SiteName"].ToString();
            return View();
        }

        //GET: ViewQuotation
        public ActionResult ViewQuotation(int id)
        {

            int MainID = Convert.ToInt32(Session["MainID"]);

            //Get Quotation 
            Quotation quotation = _quotationsModel.GetSingle(id);
            ViewData["Quotation"] = quotation;

            //Get Quotation CoBroke Item
            List<QuotationCoBroke> quotationCoBroke = _quotationCoBrokesModel.GetAllRelatedQuotationId(id);
            ViewData["QuotationCoBroke"] = quotationCoBroke;

            //Get Quotation Item Description

            //New Get Quotation Item Description
            List<QuotationItemDescription> quotationItemDescription = _quotationItemDescriptionsModel.getAllRelatedIdGetAllRelatedQuotationId(id);
            List<ItemDescriptionBigTable> quotationItemDescriptionBigTable = new List<ItemDescriptionBigTable>();

            //Loop Item Description Items
            IList<SystemSetting> listItem = _settingsModel.GetAll();
            SystemSetting CategoryList = listItem.Where(e => e.Code == "QUOTATION_CATEGORIES").FirstOrDefault();

            string[] categoryList = CategoryList.Value.Split('|');

            //Start
            int countItemDescription = 1;
            int resetNumber = 1;
            foreach (QuotationItemDescription _quotationItemDescription in quotationItemDescription)//14 items
            {
                string ItemName = _quotationItemDescription.CategoryName;
                decimal ItemQty = (decimal)_quotationItemDescription.QuotationItemQty;
                decimal ItemRate = (decimal)_quotationItemDescription.QuotationItemRate;
                decimal ItemEstCost = (decimal)_quotationItemDescription.QuotationItemEstCost;
                bool IsBasic = false; //default set to false means it is not from db item.

                List<ItemDescriptionRow> ItemDescriptionRows = new List<ItemDescriptionRow>();

                if (ItemQty == null)
                {
                    ItemQty = 0;
                }

                if (ItemRate == null)
                {
                    ItemRate = 0;
                }

                if (ItemEstCost == null)
                {
                    ItemEstCost = 0;
                }


                foreach (string _categoryList in categoryList)
                {
                    if (_categoryList == _quotationItemDescription.CategoryName)
                    {
                        IsBasic = true;
                    }
                }

                if (quotationItemDescriptionBigTable.Count == 0)
                {
                    resetNumber = 1;
                    ItemDescriptionRows.Add(new ItemDescriptionRow()

NODC_OMS/NODC/Views/Customers/CustomerProfile.cshtml
@using DataAccess.POCO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = ViewData["SiteName"].ToString();
    ViewBag.PageTitle = "Update Profile";
}

<div class="page-content">
    <div class="panel">
        <div class="panel-body container-fluid">
            <div class="row row-lg">
                <div class="col-md-10">
                    <!-- Example Horizontal Form -->
                    @using (Html.BeginForm("CustomerProfile", "Customers", FormMethod.Post, new { @class = "form-horizontal" }))
                    {

                        if (Session["Result"] != null)
                        {
                            string[] result = Session["Result"].ToString().Split('|');

                            <div class="alert alert-@result[0] text-center">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                @result[1]
                            </div>

                            Session.Remove("Result");
                        }

                        <div class="form-group">
                            @Html.Label("User ID", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.TextBox("UserID", @ViewData["UserID"], new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Login ID", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.TextBox("LoginID", @ViewData["LoginID"], new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Password", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.Password("Password", null, new { @class = "form-control" })
                                @Html.ValidationMessage("Password")
                                <span class="help-block" style="color:#000;"><i class="wb-info-circle"></i> Leave Blank If No Change</span>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Repeat Password", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                @Html.Password("RepeatPassword", null, new { @class = "form-control" })
                                @Html.ValidationMessage("RepeatPassword")
                                <span class="help-block" style="color:#000;"><i class="wb-info-circle"></i> Leave Blank If No Change</span>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Status", new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Status" value="Active" disabled>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-primary margin-top-10">Save</button>
                                <button type="reset" class="btn btn-default btn-outline margin-top-10">Reset</button>
                            </div>
                        </div>
                    }
                    <!-- End Example Horizontal Form -->
                </div>
            </div>
        </div>
    </div>
</div>

NODC_OMS/NODC/Views/Customers/ListingInvoice.cshtml
@using DataAccess.POCO
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = ViewData["SiteName"].ToString();
    ViewBag.PageTitle = "My Invoices";
    ViewBag.AInvoice = "active";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel">
    <div class="panel-body container-fluid">
        <div class="row margin-top-15">
            <div class="col-xlg-12 col-md-12">
                @using (Html.BeginForm("ListingInvoice", "Customers", FormMethod.Post, new { @class = "page-search-form", @role = "search" }))
                {
                    <div class="input-search input-search-dark">
                        <button type="submit" class="input-search-icon wb-search" aria-label="Search" arial-hidden="true" id="btn-search"></button>
                        @Html.TextBox("SearchKeyword", ViewData["SearchKeyword"].ToString(), new { @class = "form-control", @placeholder = "Search by Invoice ID or Customer Name" })
                        <button type="button" class="input-search-close icon wb-close" aria-label="Close" id="btn-close"></button>
                    </div>
                }
            </div>
        </div>

        <div class="row margin-top-15">
            <div class="col-xlg-12 col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Invoice ID</th>
                                <th>Customer/Company</th>
                                <th>Date</th>
                                <th>Grand Total</th>
                                <th>Payment Made</th>
                                <th>Prepared by</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                IPagedList<Invoice> invoices = (IPagedList<Invoice>)ViewData["Invoice"];

                                if (invoices.Count > 0)
                                {
                                    int pageCount = 0;
                                    int pageSize = Convert.ToInt32(Session["PageSize"]);
                                    int i = 1;

                                    if (Session["Page"] != null)
                                    {
                                        pageCount = Convert.ToInt32(Session["Page"]) - 1;
                                    }

                                    foreach (Invoice invoice in invoices)
                                    {
                                        string col3 = invoice.Customer.CompanyName;

                                        if (string.IsNullOrEmpty(col3))
                                        {
                                            col3 = invoice.Customer.ContactPerson;
                                        }

                                        string col6 = "-";

                                        if (invoice.PaymentMade != null)
                                        {
                                            col6 = "$" + Convert.ToDecimal(invoice.PaymentMade).ToString("#,##0.00");
                                        }

                                        <tr>
                                            <td>@(i + pageCount * pageSize)</td>
                                            <td><a href="@Url.Action("ViewInvoice", new { @id = invoice.ID })" data-toggle="tooltip" data-original-title="View Invoice">@invoice.InvoiceID</a></td>
                                            <td>@col3</td>
                                            <td>@invoice.Date.ToString("dd/MM/yyyy")</td>
                                            <td>$@invoice.GrandTotalAmount.ToString("#,##0.00")</td>
                                            <td>@col6</td>
                                            <td>@invoice.PreparedBy.Name</td>
                                            <td>@invoice.Status</td>
                                        </tr>
                                        i++;
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td class="no-record" colspan="8">No record to display</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="pagination pagination-no-border">
                @Html.PagedListPager((IPagedList)ViewData["Invoice"], page => Url.Action("/ListingInvoice", "Customers", new { page, currentFilter = ViewBag.CurrentFilter }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< First", LinkToPreviousPageFormat = "< Previous", LinkToNextPageFormat = "Next >", LinkToLastPageFormat = "Last >>" })
            </div>
        </div>
    </div>
</div>

NODC_OMS/NODC/Views/Customers/ListingProject.cshtml
@using DataAccess.POCO
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = ViewData["SiteName"].ToString();
    ViewBag.PageTitle = "My Projects";
    ViewBag.AProject = "active";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel">
    <div class="panel-body container-fluid">

        <div class="row margin-top-15">
            <div class="col-xlg-12 col-md-12">
            @using (Html.BeginForm("ListingProject", "Customers", FormMethod.Post, new { @class = "page-search-form", @role = "search" }))
            {
                <div class="input-search input-search-dark">
                    <button type="submit" class="input-search-icon wb-search" aria-label="Search" arial-hidden="true" id="btn-search"></button>
                    @Html.TextBox("SearchKeyword", ViewData["SearchKeyword"].ToString(), new { @class = "form-control", @placeholder = "Search by Project ID" })
                    <button type="button" class="input-search-close icon wb-close" aria-label="Close" id="btn-close"></button>
                </div>
            }
            </div>
        </div>

        <div class="row margin-top-15">
            <div class="col-xlg-12 col-md-12">
                <!-- Table -->
                <div>

                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Project ID</th>
                                    <th>Customer/Company</th>
                                    <th>Start Date</th>
                                    <th>Project Amount</th>
                                    <th>Managed by</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>

                            @{
                                IPagedList<Project> projects = (IPagedList<Project>)ViewData["Project"];

                                List<QuotationItemDescription> quotationItemDescriptions = (List<QuotationItemDescription>)ViewData["QuotationItemDescription"];
                                List<ProjectProjectExpenses> projectExpenses = (List<ProjectProjectExpenses>)ViewData["projectExpenses"];
                                
                                if (projects.Count > 0)
                                {
                                    int count = 1;

                                    foreach (Project _projects in projects)
                                    {
                                        int col1 = count;
                                        string col2 = "-";
                                        string col3 = "-";
                                        string col4 = "-";
                                        string col5 = "0.00";
                                        string col6 = "0.00";
                                        string col7 = "-";
                                        string col8 = "-";

                                        decimal TotalProjectAmount = Convert.ToDecimal("0.00");
                                        decimal TotalExpenses = Convert.ToDecimal("0.00");

                                        foreach (QuotationItemDescription _quotationItemDescription in quotationItemDescriptions)
                                        {
                                            if (_quotationItemDescription.QuotationId == _projects.QuotationReferenceId)
                                            {
                                                TotalProjectAmount += _quotationItemDescription.QuotationItemAmount;
                                            }
                                        }

                                        foreach (ProjectProjectExpenses _projectExpenses in projectExpenses)
                                        {
                                            if (_projectExpenses.ProjectId == _projects.ID)
                                            {
                                                TotalExpenses += _projectExpenses.Cost;
                                            }
                                        }

                                        string FormattedTotalProjectAmount = TotalProjectAmount.ToString("#,##0.00");
                                        string FormattedTotalExpenses = TotalExpenses.ToString("#,##0.00");

                                        if (!string.IsNullOrEmpty(_projects.ProjectID))
                                        {
                                            col2 = _projects.ProjectID;
                                        }

                                        if (_projects.Customer != null)
                                        {
                                            col3 = _projects.Customer.ContactPerson;
                                        }

                                        if (_projects.Date != null)
                                        {
                                            col4 = Convert.ToString(_projects.Date);
                                        }

                                        col7 = _projects.Coordinator.Name;

                                        if (_projects.Status != null)
                                        {
                                            col8 = _projects.Status;
                                        }

                                        <tr>
                                            <td>@col1</td>
                                            <td><a href="@Url.Action("ViewProject", new { @id = _projects.ID })">@col2</a></td>
                                            <td>@col3</td>
                                            <td>@col4</td>
                                            <td>$@FormattedTotalProjectAmount</td>
                                            <td>@col7</td>
                                            <td>@col8</td>
                                        </tr>
                                        count++;
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td class="no-record" colspan="8">No record to display</td>
                                    </tr>
                                }
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- End Table -->
            </div>

            <div class="pagination pagination-no-border">
                @Html.PagedListPager((IPagedList)ViewData["Project"], page => Url.Action("/ListingProject", "Customers", new { page, currentFilter = ViewBag.CurrentFilter }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< First", LinkToPreviousPageFormat = "< Previous", LinkToNextPageFormat = "Next >", LinkToLastPageFormat = "Last >>" })
            </div>

        </div>
    </div>
</div>